#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define PRODUCTION_ID_COUNT 31

enum {
  anon_sym_enum = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_struct = 7,
  anon_sym_COLON = 8,
  sym_external_func_decl = 9,
  sym_operator_decl = 10,
  sym_syscall_decl = 11,
  sym_function_decl = 12,
  sym_const_decl = 13,
  anon_sym_COLON_COLON = 14,
  anon_sym_DOT = 15,
  anon_sym_STAR = 16,
  sym_module_identifier = 17,
  sym_identifier = 18,
  sym_source_file = 19,
  sym_module_nodes = 20,
  sym_enum_decl = 21,
  sym_struct_decl = 22,
  sym_enum_assoc = 23,
  sym_ktype = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_enum_decl_repeat1 = 26,
  aux_sym_enum_decl_repeat2 = 27,
  aux_sym_struct_decl_repeat1 = 28,
  aux_sym_enum_assoc_repeat1 = 29,
  aux_sym_ktype_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_enum] = "enum",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_struct] = "struct",
  [anon_sym_COLON] = ":",
  [sym_external_func_decl] = "external_func_decl",
  [sym_operator_decl] = "operator_decl",
  [sym_syscall_decl] = "syscall_decl",
  [sym_function_decl] = "function_decl",
  [sym_const_decl] = "const_decl",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_DOT] = ".",
  [anon_sym_STAR] = "*",
  [sym_module_identifier] = "module_identifier",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_module_nodes] = "module_nodes",
  [sym_enum_decl] = "enum_decl",
  [sym_struct_decl] = "struct_decl",
  [sym_enum_assoc] = "enum_assoc",
  [sym_ktype] = "ktype",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_enum_decl_repeat1] = "enum_decl_repeat1",
  [aux_sym_enum_decl_repeat2] = "enum_decl_repeat2",
  [aux_sym_struct_decl_repeat1] = "struct_decl_repeat1",
  [aux_sym_enum_assoc_repeat1] = "enum_assoc_repeat1",
  [aux_sym_ktype_repeat1] = "ktype_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_external_func_decl] = sym_external_func_decl,
  [sym_operator_decl] = sym_operator_decl,
  [sym_syscall_decl] = sym_syscall_decl,
  [sym_function_decl] = sym_function_decl,
  [sym_const_decl] = sym_const_decl,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_module_identifier] = sym_module_identifier,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_module_nodes] = sym_module_nodes,
  [sym_enum_decl] = sym_enum_decl,
  [sym_struct_decl] = sym_struct_decl,
  [sym_enum_assoc] = sym_enum_assoc,
  [sym_ktype] = sym_ktype,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_enum_decl_repeat1] = aux_sym_enum_decl_repeat1,
  [aux_sym_enum_decl_repeat2] = aux_sym_enum_decl_repeat2,
  [aux_sym_struct_decl_repeat1] = aux_sym_struct_decl_repeat1,
  [aux_sym_enum_assoc_repeat1] = aux_sym_enum_assoc_repeat1,
  [aux_sym_ktype_repeat1] = aux_sym_ktype_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_external_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_syscall_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_const_decl] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_module_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module_nodes] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_assoc] = {
    .visible = true,
    .named = true,
  },
  [sym_ktype] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_assoc_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ktype_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_assoc_type = 1,
  field_enum_case_decl = 2,
  field_enum_cases = 3,
  field_enum_decl = 4,
  field_field = 5,
  field_module_path = 6,
  field_name = 7,
  field_node_decl = 8,
  field_parametric_type = 9,
  field_pointer = 10,
  field_struct_decl = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assoc_type] = "assoc_type",
  [field_enum_case_decl] = "enum_case_decl",
  [field_enum_cases] = "enum_cases",
  [field_enum_decl] = "enum_decl",
  [field_field] = "field",
  [field_module_path] = "module_path",
  [field_name] = "name",
  [field_node_decl] = "node_decl",
  [field_parametric_type] = "parametric_type",
  [field_pointer] = "pointer",
  [field_struct_decl] = "struct_decl",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 1},
  [10] = {.index = 11, .length = 3},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 4},
  [13] = {.index = 20, .length = 2},
  [14] = {.index = 22, .length = 2},
  [15] = {.index = 24, .length = 4},
  [16] = {.index = 28, .length = 5},
  [17] = {.index = 33, .length = 5},
  [18] = {.index = 38, .length = 2},
  [19] = {.index = 40, .length = 3},
  [20] = {.index = 43, .length = 5},
  [21] = {.index = 48, .length = 2},
  [22] = {.index = 50, .length = 6},
  [23] = {.index = 56, .length = 6},
  [24] = {.index = 62, .length = 3},
  [25] = {.index = 65, .length = 7},
  [26] = {.index = 72, .length = 4},
  [27] = {.index = 76, .length = 3},
  [28] = {.index = 79, .length = 5},
  [29] = {.index = 84, .length = 4},
  [30] = {.index = 88, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_node_decl, 0},
  [1] =
    {field_enum_decl, 0},
  [2] =
    {field_struct_decl, 0},
  [3] =
    {field_node_decl, 0, .inherited = true},
  [4] =
    {field_node_decl, 0, .inherited = true},
    {field_node_decl, 1, .inherited = true},
  [6] =
    {field_name, 1},
  [7] =
    {field_enum_case_decl, 0},
  [8] =
    {field_enum_cases, 3},
    {field_name, 1},
  [10] =
    {field_enum_cases, 1},
  [11] =
    {field_enum_cases, 3},
    {field_enum_cases, 4, .inherited = true},
    {field_name, 1},
  [14] =
    {field_enum_cases, 0, .inherited = true},
    {field_enum_cases, 1, .inherited = true},
  [16] =
    {field_name, 1},
    {field_parametric_type, 2},
    {field_parametric_type, 3},
    {field_parametric_type, 4},
  [20] =
    {field_pointer, 0},
    {field_pointer, 1},
  [22] =
    {field_assoc_type, 2},
    {field_enum_case_decl, 0},
  [24] =
    {field_field, 3},
    {field_field, 4},
    {field_field, 5},
    {field_name, 1},
  [28] =
    {field_enum_cases, 6},
    {field_name, 1},
    {field_parametric_type, 2},
    {field_parametric_type, 3},
    {field_parametric_type, 4},
  [33] =
    {field_name, 1},
    {field_parametric_type, 2},
    {field_parametric_type, 3},
    {field_parametric_type, 4},
    {field_parametric_type, 5},
  [38] =
    {field_module_path, 0},
    {field_module_path, 1},
  [40] =
    {field_assoc_type, 2},
    {field_assoc_type, 3},
    {field_enum_case_decl, 0},
  [43] =
    {field_field, 3},
    {field_field, 4},
    {field_field, 5},
    {field_field, 6, .inherited = true},
    {field_name, 1},
  [48] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
  [50] =
    {field_enum_cases, 6},
    {field_enum_cases, 7, .inherited = true},
    {field_name, 1},
    {field_parametric_type, 2},
    {field_parametric_type, 3},
    {field_parametric_type, 4},
  [56] =
    {field_enum_cases, 7},
    {field_name, 1},
    {field_parametric_type, 2},
    {field_parametric_type, 3},
    {field_parametric_type, 4},
    {field_parametric_type, 5},
  [62] =
    {field_module_path, 0},
    {field_module_path, 1},
    {field_module_path, 2},
  [65] =
    {field_enum_cases, 7},
    {field_enum_cases, 8, .inherited = true},
    {field_name, 1},
    {field_parametric_type, 2},
    {field_parametric_type, 3},
    {field_parametric_type, 4},
    {field_parametric_type, 5},
  [72] =
    {field_field, 6},
    {field_field, 7},
    {field_field, 8},
    {field_name, 1},
  [76] =
    {field_field, 1},
    {field_field, 2},
    {field_field, 3},
  [79] =
    {field_field, 6},
    {field_field, 7},
    {field_field, 8},
    {field_field, 9, .inherited = true},
    {field_name, 1},
  [84] =
    {field_field, 7},
    {field_field, 8},
    {field_field, 9},
    {field_name, 1},
  [88] =
    {field_field, 7},
    {field_field, 8},
    {field_field, 9},
    {field_field, 10, .inherited = true},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == ')') ADVANCE(39);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == 'c') ADVANCE(19);
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(21);
      if (lookahead == 's') ADVANCE(28);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(53);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(53);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(33);
      if (lookahead == 'x') ADVANCE(32);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == 'y') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(50);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_external_func_decl);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_operator_decl);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_syscall_decl);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_function_decl);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_const_decl);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_module_identifier);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_external_func_decl] = ACTIONS(1),
    [sym_operator_decl] = ACTIONS(1),
    [sym_syscall_decl] = ACTIONS(1),
    [sym_function_decl] = ACTIONS(1),
    [sym_const_decl] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_module_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(102),
    [sym_module_nodes] = STATE(7),
    [sym_enum_decl] = STATE(8),
    [sym_struct_decl] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_enum] = ACTIONS(5),
    [anon_sym_struct] = ACTIONS(7),
    [sym_external_func_decl] = ACTIONS(9),
    [sym_operator_decl] = ACTIONS(9),
    [sym_syscall_decl] = ACTIONS(9),
    [sym_function_decl] = ACTIONS(9),
    [sym_const_decl] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_enum,
    ACTIONS(7), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym_module_nodes,
    STATE(8), 1,
      sym_enum_decl,
    STATE(9), 1,
      sym_struct_decl,
    ACTIONS(9), 5,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [29] = 8,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(18), 1,
      anon_sym_struct,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym_module_nodes,
    STATE(8), 1,
      sym_enum_decl,
    STATE(9), 1,
      sym_struct_decl,
    ACTIONS(21), 5,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [58] = 1,
    ACTIONS(24), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [69] = 1,
    ACTIONS(26), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [80] = 1,
    ACTIONS(28), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [91] = 1,
    ACTIONS(30), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [102] = 1,
    ACTIONS(32), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [113] = 1,
    ACTIONS(34), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [124] = 1,
    ACTIONS(36), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [135] = 1,
    ACTIONS(38), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [146] = 1,
    ACTIONS(40), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [157] = 1,
    ACTIONS(42), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [168] = 1,
    ACTIONS(44), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [179] = 1,
    ACTIONS(46), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [190] = 1,
    ACTIONS(48), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [201] = 1,
    ACTIONS(50), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [212] = 1,
    ACTIONS(52), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [223] = 1,
    ACTIONS(54), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [234] = 1,
    ACTIONS(56), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [245] = 1,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [256] = 1,
    ACTIONS(60), 8,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
      sym_external_func_decl,
      sym_operator_decl,
      sym_syscall_decl,
      sym_function_decl,
      sym_const_decl,
  [267] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(44), 1,
      sym_ktype,
  [280] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(78), 1,
      sym_ktype,
  [293] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(53), 1,
      sym_ktype,
  [306] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(86), 1,
      sym_ktype,
  [319] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(58), 1,
      sym_ktype,
  [332] = 2,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [341] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(61), 1,
      sym_ktype,
  [354] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(67), 1,
      sym_ktype,
  [367] = 2,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [376] = 2,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [385] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(71), 1,
      sym_ktype,
  [398] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(49), 1,
      sym_ktype,
  [411] = 4,
    ACTIONS(62), 1,
      anon_sym_STAR,
    ACTIONS(64), 1,
      sym_module_identifier,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(52), 1,
      sym_ktype,
  [424] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_enum_assoc_repeat1,
  [434] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(84), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_enum_assoc_repeat1,
  [444] = 3,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_enum_decl_repeat1,
  [454] = 1,
    ACTIONS(90), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [460] = 3,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 1,
      sym_identifier,
    STATE(50), 1,
      sym_enum_assoc,
  [470] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(96), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_enum_assoc_repeat1,
  [480] = 3,
    ACTIONS(98), 1,
      anon_sym_COMMA,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_enum_decl_repeat1,
  [490] = 3,
    ACTIONS(103), 1,
      anon_sym_COLON_COLON,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(55), 1,
      aux_sym_ktype_repeat1,
  [500] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_enum_assoc_repeat1,
  [510] = 1,
    ACTIONS(109), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [516] = 3,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_enum_decl_repeat2,
  [526] = 1,
    ACTIONS(116), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [532] = 3,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_struct_decl_repeat1,
  [542] = 3,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_struct_decl_repeat1,
  [552] = 3,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_enum_decl_repeat2,
  [562] = 3,
    ACTIONS(94), 1,
      sym_identifier,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym_enum_assoc,
  [572] = 1,
    ACTIONS(130), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [578] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_enum_assoc_repeat1,
  [588] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_enum_assoc_repeat1,
  [598] = 3,
    ACTIONS(103), 1,
      anon_sym_COLON_COLON,
    ACTIONS(136), 1,
      anon_sym_DOT,
    STATE(70), 1,
      aux_sym_ktype_repeat1,
  [608] = 1,
    ACTIONS(138), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [614] = 3,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_enum_decl_repeat2,
  [624] = 3,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      aux_sym_struct_decl_repeat1,
  [634] = 3,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_struct_decl_repeat1,
  [644] = 1,
    ACTIONS(146), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [650] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_enum_assoc_repeat1,
  [660] = 3,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_struct_decl_repeat1,
  [670] = 2,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [678] = 3,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_enum_decl_repeat2,
  [688] = 3,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_enum_decl_repeat1,
  [698] = 3,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      aux_sym_enum_decl_repeat2,
  [708] = 3,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_struct_decl_repeat1,
  [718] = 3,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      aux_sym_enum_decl_repeat1,
  [728] = 3,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_enum_decl_repeat2,
  [738] = 3,
    ACTIONS(168), 1,
      anon_sym_COLON_COLON,
    ACTIONS(171), 1,
      anon_sym_DOT,
    STATE(70), 1,
      aux_sym_ktype_repeat1,
  [748] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_enum_assoc_repeat1,
  [758] = 1,
    ACTIONS(175), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [764] = 3,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_enum_decl_repeat1,
  [774] = 3,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_enum_assoc_repeat1,
  [784] = 3,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_enum_decl_repeat2,
  [794] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_struct_decl_repeat1,
  [804] = 3,
    ACTIONS(94), 1,
      sym_identifier,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_enum_assoc,
  [814] = 1,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [819] = 1,
    ACTIONS(171), 2,
      anon_sym_COLON_COLON,
      anon_sym_DOT,
  [824] = 1,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [829] = 2,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
  [836] = 1,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [841] = 2,
    ACTIONS(94), 1,
      sym_identifier,
    STATE(80), 1,
      sym_enum_assoc,
  [848] = 1,
    ACTIONS(101), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [853] = 1,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [858] = 1,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [863] = 2,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
  [870] = 1,
    ACTIONS(209), 1,
      sym_identifier,
  [874] = 1,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
  [878] = 1,
    ACTIONS(213), 1,
      sym_identifier,
  [882] = 1,
    ACTIONS(215), 1,
      sym_identifier,
  [886] = 1,
    ACTIONS(217), 1,
      anon_sym_COLON,
  [890] = 1,
    ACTIONS(219), 1,
      anon_sym_COLON,
  [894] = 1,
    ACTIONS(221), 1,
      sym_identifier,
  [898] = 1,
    ACTIONS(223), 1,
      sym_identifier,
  [902] = 1,
    ACTIONS(225), 1,
      sym_identifier,
  [906] = 1,
    ACTIONS(227), 1,
      sym_identifier,
  [910] = 1,
    ACTIONS(229), 1,
      anon_sym_COLON,
  [914] = 1,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
  [918] = 1,
    ACTIONS(233), 1,
      sym_identifier,
  [922] = 1,
    ACTIONS(235), 1,
      sym_identifier,
  [926] = 1,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
  [930] = 1,
    ACTIONS(239), 1,
      sym_module_identifier,
  [934] = 1,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
  [938] = 1,
    ACTIONS(243), 1,
      sym_identifier,
  [942] = 1,
    ACTIONS(245), 1,
      anon_sym_COLON,
  [946] = 1,
    ACTIONS(247), 1,
      sym_identifier,
  [950] = 1,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 69,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 91,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 113,
  [SMALL_STATE(10)] = 124,
  [SMALL_STATE(11)] = 135,
  [SMALL_STATE(12)] = 146,
  [SMALL_STATE(13)] = 157,
  [SMALL_STATE(14)] = 168,
  [SMALL_STATE(15)] = 179,
  [SMALL_STATE(16)] = 190,
  [SMALL_STATE(17)] = 201,
  [SMALL_STATE(18)] = 212,
  [SMALL_STATE(19)] = 223,
  [SMALL_STATE(20)] = 234,
  [SMALL_STATE(21)] = 245,
  [SMALL_STATE(22)] = 256,
  [SMALL_STATE(23)] = 267,
  [SMALL_STATE(24)] = 280,
  [SMALL_STATE(25)] = 293,
  [SMALL_STATE(26)] = 306,
  [SMALL_STATE(27)] = 319,
  [SMALL_STATE(28)] = 332,
  [SMALL_STATE(29)] = 341,
  [SMALL_STATE(30)] = 354,
  [SMALL_STATE(31)] = 367,
  [SMALL_STATE(32)] = 376,
  [SMALL_STATE(33)] = 385,
  [SMALL_STATE(34)] = 398,
  [SMALL_STATE(35)] = 411,
  [SMALL_STATE(36)] = 424,
  [SMALL_STATE(37)] = 434,
  [SMALL_STATE(38)] = 444,
  [SMALL_STATE(39)] = 454,
  [SMALL_STATE(40)] = 460,
  [SMALL_STATE(41)] = 470,
  [SMALL_STATE(42)] = 480,
  [SMALL_STATE(43)] = 490,
  [SMALL_STATE(44)] = 500,
  [SMALL_STATE(45)] = 510,
  [SMALL_STATE(46)] = 516,
  [SMALL_STATE(47)] = 526,
  [SMALL_STATE(48)] = 532,
  [SMALL_STATE(49)] = 542,
  [SMALL_STATE(50)] = 552,
  [SMALL_STATE(51)] = 562,
  [SMALL_STATE(52)] = 572,
  [SMALL_STATE(53)] = 578,
  [SMALL_STATE(54)] = 588,
  [SMALL_STATE(55)] = 598,
  [SMALL_STATE(56)] = 608,
  [SMALL_STATE(57)] = 614,
  [SMALL_STATE(58)] = 624,
  [SMALL_STATE(59)] = 634,
  [SMALL_STATE(60)] = 644,
  [SMALL_STATE(61)] = 650,
  [SMALL_STATE(62)] = 660,
  [SMALL_STATE(63)] = 670,
  [SMALL_STATE(64)] = 678,
  [SMALL_STATE(65)] = 688,
  [SMALL_STATE(66)] = 698,
  [SMALL_STATE(67)] = 708,
  [SMALL_STATE(68)] = 718,
  [SMALL_STATE(69)] = 728,
  [SMALL_STATE(70)] = 738,
  [SMALL_STATE(71)] = 748,
  [SMALL_STATE(72)] = 758,
  [SMALL_STATE(73)] = 764,
  [SMALL_STATE(74)] = 774,
  [SMALL_STATE(75)] = 784,
  [SMALL_STATE(76)] = 794,
  [SMALL_STATE(77)] = 804,
  [SMALL_STATE(78)] = 814,
  [SMALL_STATE(79)] = 819,
  [SMALL_STATE(80)] = 824,
  [SMALL_STATE(81)] = 829,
  [SMALL_STATE(82)] = 836,
  [SMALL_STATE(83)] = 841,
  [SMALL_STATE(84)] = 848,
  [SMALL_STATE(85)] = 853,
  [SMALL_STATE(86)] = 858,
  [SMALL_STATE(87)] = 863,
  [SMALL_STATE(88)] = 870,
  [SMALL_STATE(89)] = 874,
  [SMALL_STATE(90)] = 878,
  [SMALL_STATE(91)] = 882,
  [SMALL_STATE(92)] = 886,
  [SMALL_STATE(93)] = 890,
  [SMALL_STATE(94)] = 894,
  [SMALL_STATE(95)] = 898,
  [SMALL_STATE(96)] = 902,
  [SMALL_STATE(97)] = 906,
  [SMALL_STATE(98)] = 910,
  [SMALL_STATE(99)] = 914,
  [SMALL_STATE(100)] = 918,
  [SMALL_STATE(101)] = 922,
  [SMALL_STATE(102)] = 926,
  [SMALL_STATE(103)] = 930,
  [SMALL_STATE(104)] = 934,
  [SMALL_STATE(105)] = 938,
  [SMALL_STATE(106)] = 942,
  [SMALL_STATE(107)] = 946,
  [SMALL_STATE(108)] = 950,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(88),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(107),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 10, .production_id = 26),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_nodes, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 11, .production_id = 28),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_nodes, 1, .production_id = 2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_nodes, 1, .production_id = 3),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 6, .production_id = 10),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 10, .production_id = 25),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 12, .production_id = 30),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 9, .production_id = 23),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 9, .production_id = 22),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 8, .production_id = 20),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 8, .production_id = 17),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 8, .production_id = 16),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 4, .production_id = 6),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 7, .production_id = 15),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, .production_id = 8),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 7, .production_id = 12),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 11, .production_id = 29),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 4, .production_id = 24),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 3, .production_id = 18),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 8, .production_id = 24),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2), SHIFT_REPEAT(90),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 7, .production_id = 24),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat2, 2, .production_id = 11), SHIFT_REPEAT(83),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat2, 2, .production_id = 11),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 7, .production_id = 18),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 2, .production_id = 13),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 6, .production_id = 18),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 5),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_assoc, 1, .production_id = 7),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ktype_repeat1, 2), SHIFT_REPEAT(103),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ktype_repeat1, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ktype, 4),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_assoc_repeat1, 2), SHIFT_REPEAT(24),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_assoc_repeat1, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, .production_id = 21), SHIFT_REPEAT(95),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, .production_id = 21),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat2, 2, .production_id = 9),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_assoc, 4, .production_id = 14),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_assoc, 5, .production_id = 19),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 4, .production_id = 27),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [237] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_Kosu(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
